# Generated by Django 4.2.1 on 2023-06-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useractivity_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='last_login',
        ),
    ]
